### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by willard-yuan** [stylixboom/alphautils#1]
Hi stylixboom,
When I try to compile it with the command `make`, it throws the following error:

``` sh
test -d . || mkdir -p .
test -d obj/Debug || mkdir -p obj/Debug
g++ -std=c++11 -Wall -fexceptions -Wall -g -I/home/willard/local/include -c imtools.cpp -o obj/Debug/imtools.o
In file included from /usr/local/include/opencv2/calib3d/calib3d.hpp:48:0,
                 from imtools.cpp:27:
/usr/local/include/opencv2/core/affine.hpp: In member function ‘void cv::Affine3<T>::rotation(const Vec3&)’:
/usr/local/include/opencv2/core/affine.hpp:241:9: error: expected primary-expression before ‘const’
         const double I[] = { 1, 0, 0, 0, 1, 0, 0, 0, 1 };
         ^
/usr/local/include/opencv2/core/affine.hpp:241:9: error: expected ‘;’ before ‘const’
In file included from /usr/include/c++/4.8/complex.h:36:0,
                 from /usr/include/lapacke.h:73,
                 from lapwrap.h:12,
                 from imtools.cpp:23:
/usr/local/include/opencv2/core/affine.hpp:257:50: error: unable to find numeric literal operator ‘operator"" iF’
             R.val[k] = static_cast<float_type>(c*I[k] + c1*rrt[k] + s*_r_x_[k]);
                                                  ^
make: *** [obj/Debug/imtools.o] Error 1
```

My OpenCV's version is 2.4.11, and I have installed lapacke library. Could you tell me how to fix the compiling bug?

**Comment by stylixboom** [comment]
Hi willard-yuan,

Well, this might be the dependency issue, it's hard to tell from this compiling problem.

However,
this is the cmake command for "lapack" that I recommend you to use with opencv (especially turning of optimized lapack)
cmake -D BUILD_SHARED_LIBS=ON -D CMAKE_BUILD_TYPE=Release -D LAPACKE=ON -D LAPACKE_WITH_TMG=ON -D USE_OPTIMIZED_BLAS=OFF -D USE_OPTIMIZED_LAPACK=OFF ..

and this is the cmake command that I use and it works with my "opencv"
cmake -D BUILD_DOCS=OFF -D BUILD_EXAMPLES=ON -D BUILD_JASPER=ON -D BUILD_JPEG=ON -D BUILD_OPENEXR=ON -D BUILD_PERF_TESTS=ON -D BUILD_PNG=ON -D BUILD_TBB=OFF -D BUILD_TESTS=OFF -D BUILD_TIFF=ON -D BUILD_WITH_DEBUG_INFO=OFF -D BUILD_ZLIB=ON -D BUILD_opencv_java=OFF -D CMAKE_BUILD_TYPE=Release -D BUILD_opencv_world=OFF -D ENABLE_AVX=OFF -D ENABLE_FAST_MATH=ON -D ENABLE_SSE=ON -D ENABLE_SSE2=ON -D ENABLE_SSE3=ON -D ENABLE_SSE41=ON -D ENABLE_SSE42=ON -D ENABLE_SSSE3=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_TESTS=ON -D WITH_CUBLAS=OFF -D WITH_CUDA=OFF -D WITH_CUFFT=OFF -D WITH_FFMPEG=ON -D WITH_GTK=OFF -D WITH_JASPER=ON -D WITH_JPEG=ON -D WITH_OPENEXR=ON -D WITH_OPENGL=ON -D WITH_OPENMP=ON -D WITH_PNG=ON -D WITH_QT=OFF -D WITH_TBB=OFF -D WITH_TIFF=ON ..

I cannot say this is your working configuration, you may need to check more what you missed.

**Comment by willard-yuan** [comment]
Hi stylixboom,

Thanks for your great help. I'll try it on later.
